//// File Name: LAM__0.02.h
//// File Version: 0.02
// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_LAM_H_GEN_
#define RCPP_LAM_H_GEN_

#include "LAM_RcppExports.h"

#endif // RCPP_LAM_H_GEN_
