## File Name: RcppExports.R
## File Version: 0.08
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lam_loglike_mvnorm_rcpp <- function(M, S, mu, Sigma, n, use_log, lambda, ginv, eps) {
    .Call('_LAM_lam_loglike_mvnorm_rcpp', PACKAGE = 'LAM', M, S, mu, Sigma, n, use_log, lambda, ginv, eps)
}

lam_loglike_mvnorm_na_pattern_rcpp <- function(suff_stat, mu, Sigma, use_log, lambda, ginv, eps) {
    .Call('_LAM_lam_loglike_mvnorm_na_pattern_rcpp', PACKAGE = 'LAM', suff_stat, mu, Sigma, use_log, lambda, ginv, eps)
}

mlnormal_proc_variance_shortcut_Z_restructure <- function(Z_list, update_dim, start_orig, end_orig, dim_Z_index, Z_index, orig_id, dim_id) {
    .Call('_LAM_mlnormal_proc_variance_shortcut_Z_restructure', PACKAGE = 'LAM', Z_list, update_dim, start_orig, end_orig, dim_Z_index, Z_index, orig_id, dim_id)
}

mlnormal_proc_variance_shortcut_XY_restructure <- function(freq_id, y, X, G) {
    .Call('_LAM_mlnormal_proc_variance_shortcut_XY_restructure', PACKAGE = 'LAM', freq_id, y, X, G)
}

mlnormal_update_V_rcpp_helper <- function(Z_list, Z_index, dim_id, dim_Z_index, startIndex, endIndex, N, max_dim, do_compute, theta, use_ginverse) {
    .Call('_LAM_mlnormal_update_V_rcpp_helper', PACKAGE = 'LAM', Z_list, Z_index, dim_id, dim_Z_index, startIndex, endIndex, N, max_dim, do_compute, theta, use_ginverse)
}

mlnormal_update_beta_rcpp_helper <- function(dim_id, startIndex, endIndex, G, X, y, V1) {
    .Call('_LAM_mlnormal_update_beta_rcpp_helper', PACKAGE = 'LAM', dim_id, startIndex, endIndex, G, X, y, V1)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_LAM_RcppExport_registerCCallable', PACKAGE = 'LAM')
})
