# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lam_rcpp_loglike_mvnorm <- function(M, S, mu, Sigma, n, use_log, lambda, ginv, eps) {
    .Call('_LAM_lam_rcpp_loglike_mvnorm', PACKAGE = 'LAM', M, S, mu, Sigma, n, use_log, lambda, ginv, eps)
}

lam_rcpp_loglike_mvnorm_na_pattern_rcpp <- function(suff_stat, mu, Sigma, use_log, lambda, ginv, eps) {
    .Call('_LAM_lam_rcpp_loglike_mvnorm_na_pattern_rcpp', PACKAGE = 'LAM', suff_stat, mu, Sigma, use_log, lambda, ginv, eps)
}

lam_rcpp_mlnormal_proc_variance_shortcut_Z_restructure <- function(Z_list, update_dim, start_orig, end_orig, dim_Z_index, Z_index, orig_id, dim_id) {
    .Call('_LAM_lam_rcpp_mlnormal_proc_variance_shortcut_Z_restructure', PACKAGE = 'LAM', Z_list, update_dim, start_orig, end_orig, dim_Z_index, Z_index, orig_id, dim_id)
}

lam_rcpp_mlnormal_proc_variance_shortcut_XY_restructure <- function(freq_id, y, X, G) {
    .Call('_LAM_lam_rcpp_mlnormal_proc_variance_shortcut_XY_restructure', PACKAGE = 'LAM', freq_id, y, X, G)
}

lam_rcpp_mlnormal_update_V <- function(Z_list, Z_index, dim_id, dim_Z_index, startIndex, endIndex, N, max_dim, do_compute, theta, use_ginverse) {
    .Call('_LAM_lam_rcpp_mlnormal_update_V', PACKAGE = 'LAM', Z_list, Z_index, dim_id, dim_Z_index, startIndex, endIndex, N, max_dim, do_compute, theta, use_ginverse)
}

lam_rcpp_mlnormal_update_beta <- function(dim_id, startIndex, endIndex, G, X, y, V1) {
    .Call('_LAM_lam_rcpp_mlnormal_update_beta', PACKAGE = 'LAM', dim_id, startIndex, endIndex, G, X, y, V1)
}

